#!/bin/bash
# make sure we start with fresh build
echo "Making sure we start with fresh environment..."
./cleanup

# build
echo "Building libTrot.a..."
cd trotLib
gcc -O3 -DTEST_PRECOND=1 -fprofile-arcs -ftest-coverage -Wall -Werror -Wextra -c trotListPrimary.c -o trotListPrimary.o
ar rcs libTrot.a *.o
cd ..

echo "Building trotTest..."
gcc -DTEST_PRECOND=1 -Wall -Werror -Wextra -I trotLib -c trotTest/testMain.c -o trotTest/testMain.o
gcc -fprofile-arcs trotTest/testMain.o trotLib/libTrot.a -o trotTest/trotTest

